name: enayas_app
description: A new Flutter project.

 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2

  get: ^4.6.5
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2
  dio:
  get_storage: ^2.1.1
  fluttertoast: ^8.2.1
  lottie: ^2.3.2
  flutter_html: ^2.2.1
  geolocator:
  geocoding:
  image_picker: ^0.8.7+2


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 


 
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - images/a_dot_ham.jpeg
 